spring:
  datasource:
    username: root
    password: q1w2e3r4
    url: jdbc:mysql://localhost:3306/db_naturassp?userTimezone=true&serverTimerzone=America/Sap_Paulo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true